### 1. Guardar un nuevo cronograma
POST http://localhost:8080/api/cronogramas
Content-Type: application/json

{
  "monto": 1500.00,
  "cuotasTotales": 12,
  "diaPago": 15,
  "diaCierre": 28,
  "fechaCompra": "2026-09-14",
  "ted": 0.02
}